[package]
name = "r2d2_mysql_batis"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["macros"]

[dependencies]
macros = {path = "macros"}
tokio = { version = "1.35.1", features = ["full"] }
once_cell = "1.19.0"
r2d2_mysql = "24.0.0"
